### ISSUE TITLE
Using unpack in `get` task

### ISSUE THREAD

**Issue by goutamtadi1** [frodenas/gcs-resource#13]
Hi,

I have been using unpack as shown below for the `get` task:

```yaml
- get: tar-ball
  params:
    unpack: true
```
However, I don't see the tar ball being unpacked/untarred. Am I missing something here?

Thanks,
Goutam Tadi
