### ISSUE TITLE
400 error

### ISSUE THREAD

**Issue by ghost** [frodenas/gcs-resource#17]
I am receiving the following error message when trying to use the put step:
```
1.86 MiB / 1.86 MiB [===================================] 100.00% 4.17 MiB/s 0s
error running command: googleapi: Error 400: Required, required
```

Here is my configuration:
```yaml
- name: m2-bucket
  type: google-cloud-storage
  source:
    regex: m2_tar/m2/m2.tar.gz
    bucket: {{bucket_name}}
    json_key: {{bucket_private_key}}
```

```yaml
- name: google-cloud-storage
  type: docker-image
  source:
    repository: frodenas/gcs-resource
```

```yaml
    - put: m2-bucket
      params:
        file: ./m2_tar/m2/m2.tar.gz
```

Any ideas on what could be wrong? Thank you in advance!
