### ISSUE TITLE
Use version from previous get-resource

### ISSUE THREAD

**Issue by stevenvegt** [frodenas/gcs-resource#19]
We use this repo to version our npm-cache. The package.json file does not chance with every push to the repository so we would like to check for the package.json resource version and fetch that one. Using the value from the `.git/short_ref` from the git-resource would be very usefull for us.

I imagine something like this:
```yaml
resources:
- name: app-npm-cache
  type: gcs-resource
  source:
    regexp: app-npm-cache/node-modules-v(.*).tar

- name: package-json-version
  type: git
  source:
    paths:
      - package.json

jobs:  
  plan:
  - get: github-source
    trigger: true # Perform on changes of the source-code
  - get: package-json-version
  - get: app-npm-cache
    version: { version_from_file: "package-json-version/.git/short_ref" }
```
Lets say the `short_ref` has the value `1234` then the gcs-resource will search for the file `app-npm-cache/node-modules-v1234.tar`
