### ISSUE TITLE
Issue with pulling/pushing to Google Cloud Storage

### ISSUE THREAD

**Issue by jamesmaidment** [frodenas/gcs-resource#2]
Concourse Version: v2.2.1

When pulling or pushing to GCS I recieve the following error:

`json: cannot unmarshal number into Go value of type string`

Resource config:

```
resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: plan
    type: gcs-resource
    source:
      bucket: cibucket
      json_key: {{gcs_service_account}}
      versioned_file: terraform.tfplan
```

This issue does not occur when using `regexp` instead of `versioned_file`.
