### ISSUE TITLE
Version grabs latest, not specified version

### ISSUE THREAD

**Issue by professor** [frodenas/gcs-resource#20]
We expect gcs-resource to pull in the version specified with the following code. 
```
- name: harbor-tile
  type: gcs-resource
  source:
     regexp: harbor-container-registry-(.*).pivotal

...
    - get: harbor-tile
       params:
           version: 1.6.0-build.35
```

When there are two files in a bucket, however, the latest semver was pull in instead.
```
harbor-container-registry-1.6.0-build.35.pivotal
harbor-container-registry-1.6.3-build.3.pivotal
```

Here is a workaround:
```
- name: harbor-tile
  type: gcs-resource
  source:
     regexp: harbor-container-registry-(1.6.0-build.35).pivotal
...
    - get: harbor-tile
       params:
           version: 1.6.0-build.35
```
