### ISSUE TITLE
Network unreachable

### ISSUE THREAD

**Issue by danpalmer** [frodenas/gcs-resource#24]
We seem to be getting errors network errors, both in the resource check, and in `put`s to the resource. The first error here is about failure to do auth, but it seems to just be wrapping a network error.

I'm testing this with the Concourse quickstart, on version 4.2.3, running in Docker 18 on a Mac.

It looks like this could be to do with IPv6 – some GitHub issues suggest it's not fully supported on Docker Desktop yet. If that is the case though, I'm not sure why `gcs-resource` would be getting an IPv6 address to use in the first place?

Would appreciate any help you might be able to provide. I'm not certain if this is a `gcs-resource` problem specifically, but so far this is the first time I've seen anything like this issue with any Concourse resources, so I thought this would be the best place to start.

```
~/concourse > fly -t thread cr -r thread/schema.build
error: check failed with exit status '1':
error running command: Get https://www.googleapis.com/storage/v1/b/thread-build-artifacts?alt=json: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: dial tcp [<ipv6-address>]:443: connect: network is unreachable
```

The config looks like this (trimmed unnecessary jobs and tasks for clarity):

```yaml
---
resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: backend.git
    type: git
    source:
      uri: git@github.com:owner/repo.git
      branch: master
      private_key: ((github_private_key))

  - name: api-schema.build
    type: gcs-resource
    source:
      bucket: ((gcs_bucket))
      json_key: ((gcs_key))
      versioned_file: api-schema.build/local.graphql.json

jobs:
  - name: backend
    plan:
      - get: backend.git
        trigger: true
      - task: backend-build
        image: backend-build.docker
        config:
          platform: linux
          inputs:
            - name: backend.git
          outputs:
            - name: api-schema.build
          run:
            path: backend.git/scripts/output-schema.sh
      - put: api-schema.build
        params:
          file: api-schema.build/local.graphql.json
```

I'm fairly new to Concourse, so if there's a particular thing that I can provide to help debug this, please do let me know.

**Comment by danpalmer** [comment]
Ok, I've done some more investigation. I pulled the container manually, constructed some JSON that approximated what Concourse would be sending to the check command, and ran this:

```shell
~/concourse > pbpaste | docker run -i --rm frodenas/gcs-resource /opt/resource/check
[]
```

This looks like it's working fine. There are no errors, and its printing an empty list of versions, which happens to be correct for the versioned file path that I gave it.

This is puzzling, I'm not sure what's different about the running environment within Concourse. I ran this on the same Docker daemon, so it shouldn't be a configuration thing there I don't think.

**Comment by adam-power** [comment]
I am having this same issue using the [concourse-docker](https://github.com/concourse/concourse-docker) repo locally on my Mac, version 5.1.0.

The exact error is:

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
 error running command: Get https://www.googleapis.com/storage/v1/b/my-bucket?alt=json: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: dial tcp [<REDACTED>]:443: connect: network is unreachable
```

This seems to be intermittent.  I got check to succeed once, but now the error is back and I can't get rid of it.

My pipeline looks something like this:

```yaml
---
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: tfstate-file
  type: gcs
  source:
    bucket: ((bucket-name))
    json_key: ((gcp-key))
    versioned_file: terraform.tfstate
    initial_version: 0

jobs:
- name: pave-infrastructure
  plan:
  - aggregate:
    - get: tfstate-file
      trigger: true
  - task: pave-infrastructure
    ...
    ensure:
      put: tfstate-file
      params:
        file: tfstate-output/terraform.tfstate
```
