### ISSUE TITLE
Access a filename in a gcs bucket seems broken

### ISSUE THREAD

**Issue by professor** [frodenas/gcs-resource#39]
Context, I need to modify an existing pipeline to grab the specific version of a file, in this case `kubo-pipeline-store/dev-builds/kubo-deployment-0.37.0-dev.5.tgz`

After looking at the readme for `IN`, I thought this would work:
```
- name: kubo-deployment
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    filename: dev-builds/kubo-deployment-0.37.0-dev.5.tgz
```

However, it did not. Here is my work-around:

```
- name: kubo-deployment
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    regexp: dev-builds/kubo-deployment-(.*).tgz
    version: 0.37.0-dev.5
```

**Comment by professor** [comment]
Because of https://github.com/frodenas/gcs-resource/issues/20 bug, my work around didn't work. This work around does though....

```
- name: kubo-deployment
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    regexp: dev-builds/kubo-deployment-(0.37.0-dev.5).tgz
```
