### ISSUE TITLE
Updating versioned_file resource in two jobs at the same time results as same generation number

### ISSUE THREAD

**Issue by lubronzhan** [frodenas/gcs-resource#43]
Hi, in our pipeline, we have two jobs that will update same gcs resource. This resource is a versioned_file
```
- name: gcs-cluster-info
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: ((pks.pipeline_store))
    versioned_file: ((pks.version))/cluster/info.yml

resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: job1
  - put: gcs-cluster-info
     params:
      file: cluster/info.yml

- name: job2
  - put: gcs-cluster-info
     params:
      file: cluster/info.yml
```
In these two  pipelines jobs, the gcs-cluster-info have same generation: `gs://pipeline-store/1.9.x/cluster/info.yml#1598352097430055`
https://pks.ci.cf-app.com/teams/bosh-lifecycle-dev/pipelines/pks-api-1.9.x-bump-kubernetes-1.18.8/jobs/create-cluster-test-gcp/builds/1
https://pks.ci.cf-app.com/teams/bosh-lifecycle-dev/pipelines/pks-api-1.9.x-bump-kubernetes-1.18.8/jobs/create-cluster-test-gcp-ha/builds/1

Have anyone seen this?
